### ISSUE TITLE
Frame file binder links not working

### ISSUE THREAD

**Issue by geoffrey4444** [gwastro/PyCBC-Tutorials#2]
I'm trying to run your notebook on colab.research.google.com. I run into trouble where the binder frame file links are not working. E.g., in gw150914_audio.ipynb, the notebook tries downloading 

https://raw.githubusercontent.com/ligo-cbc/binder/master/H-H1_LOSC_4_V2-1126259446-32.gwf

which returns a 15-byte file that can't be opened. But if I replace the URL with 

https://losc.ligo.org/s/events/GW150914/H-H1_LOSC_4_V2-1126259446-32.gwf

then the notebook works as expected.

Perhaps the frame URLs need to be updated?

**Comment by ahnitz** [comment]
@geoffrey4444 You are right. I've just gone through them now to update them, and in most cases switch to the gw catalog interface. i.e. 
```
from pycbc import catalog
ts = catalog.Merger("GW150914").strain("H1")
```

**Comment by ahnitz** [comment]
@geoffrey4444 I assume this is now resolved after the update. If not please do reopen this.
