### ISSUE TITLE
gw151226_snr.ipynb:  A few minor corrections

### ISSUE THREAD

**Issue by kderakhshani** [gwastro/PyCBC-Tutorials#4]
Some minor corrections of typos that are not essential but may confuse the beginners:

**In  PyCBC-Tutorials/examples/gw151226_snr.ipynb:**

In [3]: # Generate a waveform similar to LVT151012: ------------------------> GW151226   is correct

In [8]: # Get the data for H1 from the LOSC site: ------------------------------> L1 is correct
          # Read the Hanford data and remove low-frequency content: -----> Livingston is correct
          # Let's look closer around the H1 peak: ---------------------------------> L1 is correct

**In  PyCBC-Tutorials/tutorial/4_ChisqSignificance.ipynb:**
The block In[2] is repeated.

Thank you for the wonderful tutorials.

Kamran  Derakhshani

**Comment by ahnitz** [comment]
@kderakhshani Sorry it took so, long, this slipped my mind. I think these should now be fixed. Thanks for pointing them out!
